language: rust
cache: cargo
rust:
    - 1.33.0
    - stable
    - beta
    - nightly
os:
    - linux
    - osx
matrix:
    allow_failures:
        - rust: nightly

before_install:
  - set -e
  - export RUSTFLAGS="-D warnings"
  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
    rustup self update &&
    rustup component add rustfmt clippy &&
    cargo clippy --version;
    fi

script:
  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
    cargo fmt --all -- --check &&
    cargo clippy --all --tests --examples -- --deny clippy::all;
    fi
  - export RUST_BACKTRACE=1
  - export CARGO_INCREMENTAL=1
  - export PATH="$PATH":~/.cargo/bin
  - cargo test --release --all --all-features
  - cargo test --release --all
  - cargo test --release -- --ignored
  - cargo doc --no-deps
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
    cargo test --all --release --benches;
    fi
