[package]
name = "contrie"
version = "0.1.0"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
edition = "2018"
# TODO: Keywords, readmes, stuff..

[dependencies]
crossbeam-epoch = "~0.7"

[dev-dependencies]
crossbeam-utils = "~0.6"
