[package]
name = "contrie"
version = "0.1.0"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
edition = "2018"
# TODO: Keywords, readmes, stuff..

[dependencies]
bitflags = "~1"
crossbeam-epoch = "~0.7"
# TODO: Consider what to do with the union feature. Why is it still requiring nightly?
smallvec = "~0.6"

[dev-dependencies]
crossbeam-utils = "~0.6"
proptest = "~0.9.3"
rayon = "~1"
